### ISSUE TITLE
demo 403

### ISSUE THREAD

**Issue by niccolox** [iamvery/example-ratchet-app#2]
hey

the heroku demo 403's

Server internal error

**Comment by iamvery** [comment]
You may have caught Heroku acting up. It is loading for me now. Can you try again? https://ratchet-example.herokuapp.com/articles

**Comment by niccolox** [comment]
The page loads but if I enter form data and submit I get the error

**Comment by iamvery** [comment]
@Ah, sorry for the confusion there. The page is only demo'ing template rendering with data. I tried (and maybe failed) to make that clear by adding the placeholder "non-functional example" to the inputs.
<img width="294" alt="screen shot 2017-03-24 at 10 39 35 am" src="https://cloud.githubusercontent.com/assets/79619/24301664/32bbc8cc-107e-11e7-9ce5-c6cb9144d5f1.png">

**Comment by iamvery** [comment]
Thanks for having a look at the project and taking the time to help out! ❤️

**Comment by niccolox** [comment]
Ok. Send the form to a static results page?

Anyway. Am going to try to find the time to try texas and ratchet and
phoenix

Great combination

**Comment by iamvery** [comment]
That's fair. I'll reopen the issue.

I'd love to hear what you think!

**Comment by niccolox** [comment]
The idea behind this is awesome and really amazing in its implications

Using wss and https for forms and ux in general as an alternative to
bloated javascript app monstrosities

Am thinking of ratchet phoenix and texas

Immediately i was jumping ahead to trying to implement dynamic forms /
simple forms and / or some kind of macro or dsl for forms

Its a real mind bender, a real paradigm shift imho

Pretty freakin amazing

**Comment by iamvery** [comment]
Thanks so much for the encouragement! ❤️

**Comment by niccolox** [comment]
no worries, will come back to this tech ecosystem soon
